### ISSUE TITLE
Create filter for books

### ISSUE THREAD

**Issue by RaduAlbastroiu** [FirescuOvidiu/learnLibrary#25]

**Comment by RaduAlbastroiu** [comment]
One route /api/books send parms filter={authorName: 'Ovidiu'} or filter={} (all books) or filter={_id: idfromDatabase}

**Comment by RaduAlbastroiu** [comment]
async function converToQuery(filter) {
  const newFilter = {};
  if (filter._id) {
    newFilter._id = filter._id;
  }
  if (filter.authorName) {
    newFilter.authorName = filter.authorName;
  }
 
return newFilter;
}

**Comment by RaduAlbastroiu** [comment]
filter = JSON.parse(filter)

**Comment by FirescuOvidiu** [comment]
{{base_url}}/api/book/?filter={firstName: Liviu Rebreanu}

**Comment by RaduAlbastroiu** [comment]
if (filter.title) {
    newFilter.title = { $regex: `.*${filter.title}.*`, $options: 'i' }
  }
